### ISSUE TITLE
Combining width:auto and positioning tooltips not working at the same time 

### ISSUE THREAD

**Issue by ablaette** [PolMine/polmineR#247]
Tooltips are wrongly positioned, if I use `width:auto`. The Tooltips are only at the correct position if margin-left is 50% of width. I do not yet know how to solve this.

```css
/* Tooltip text */
.tooltipping .tooltippingtext {
    visibility: hidden;
    /* width: auto; */
    width: 180px;
    background-color: #555;
    color: #fff;
    text-align: center;
    padding-left: 5px;
    padding-right: 5px;
    padding-top: 2px;
    padding-bottom: 2px;
    /* padding: 5px 0; */
    border-radius: 6px;

    /* Position the tooltip text */
    position: absolute;
    z-index: 1;
    bottom: 125%;
    left: 50%;
    /* margin-left: auto; */
    margin-left: -90px;

    /* Fade in tooltip */
    opacity: 0;
    transition: opacity 1s;
}
```
